name: Build

on: [push]

env:
  BUILD_TYPE: MinSizeRel

jobs:

# === Windows XP SDL2===
  winxp-sdl:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      shell: cmd
      run: |
        cd build
        cmake -G "Visual Studio 16 2019" -A Win32 -T v141_xp -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
        cmake --build . --config %BUILD_TYPE% --parallel

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-winxp-sdl'
        path: build/bin/tic80.exe

# === Windows SDL2 ===
  windows-sdl:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      shell: cmd
      run: |
        cd build
        cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_STUB=On ..
        cmake --build . --config %BUILD_TYPE% --parallel

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-sdl'
        path: build/bin/tic80.exe

  # === Script stubs ===

    - name: Deploy lua stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-sdl-lua-stub'
        path: build/bin/tic80lua.exe

    - name: Deploy moon stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-sdl-moon-stub'
        path: build/bin/tic80moon.exe

    - name: Deploy fennel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-sdl-fennel-stub'
        path: build/bin/tic80fennel.exe

    - name: Deploy js stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-sdl-js-stub'
        path: build/bin/tic80js.exe

    - name: Deploy wren stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-sdl-wren-stub'
        path: build/bin/tic80wren.exe

    - name: Deploy squirrel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-sdl-squirrel-stub'
        path: build/bin/tic80squirrel.exe

# === Windows SDLGPU ===
  windows-sdlgpu:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      shell: cmd
      run: |
        cd build
        cmake -G "Visual Studio 16 2019" -DBUILD_SDLGPU=On -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_STUB=On ..
        cmake --build . --config %BUILD_TYPE% --parallel

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-sdlgpu'
        path: build/bin/tic80.exe

# === Windows Sokol ===
  windows-sokol:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      shell: cmd
      run: |
        cd build
        cmake -G "Visual Studio 16 2019" -DBUILD_SDL=Off -DBUILD_SOKOL=On -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
        cmake --build . --config %BUILD_TYPE% --parallel
        cp bin/tic80-sokol.exe bin/tic80.exe

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-sokol'
        path: build/bin/tic80.exe

# === Ubuntu SDLGPU ===
  ubuntu-sdlgpu:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install libglu1-mesa-dev libasound2-dev libpulse-dev libaudio-dev libsamplerate0-dev -y

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SDLGPU=On -DBUILD_STUB=On ..
        cmake --build . --config $BUILD_TYPE --parallel
        cpack

    - name: Deploy DEB
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdlgpu-deb'
        path: build/tic80.deb

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdlgpu'
        path: build/bin/tic80

# === Ubuntu SDL2 ===
  ubuntu-sdl:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install libglu1-mesa-dev libasound2-dev libpulse-dev libaudio-dev libsamplerate0-dev -y

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_STUB=On ..
        cmake --build . --config $BUILD_TYPE --parallel
        cpack

    - name: Deploy DEB
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdl-deb'
        path: build/tic80.deb

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdl'
        path: build/bin/tic80

  # === Script stubs ===

    - name: Deploy lua stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdl-lua-stub'
        path: build/bin/tic80lua

    - name: Deploy moon stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdl-moon-stub'
        path: build/bin/tic80moon

    - name: Deploy fennel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdl-fennel-stub'
        path: build/bin/tic80fennel

    - name: Deploy js stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdl-js-stub'
        path: build/bin/tic80js

    - name: Deploy wren stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdl-wren-stub'
        path: build/bin/tic80wren

    - name: Deploy squirrel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-sdl-squirrel-stub'
        path: build/bin/tic80squirrel

# === Raspberry PI ===
  rpi:
    runs-on: ubuntu-latest
    container: nesbox/rpi-tic80:latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_STUB=On -DCMAKE_TOOLCHAIN_FILE=rpi/toolchain.cmake ..
        cmake --build . --config $BUILD_TYPE --parallel
        cpack

    - name: Deploy DEB
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi-dep'
        path: build/tic80.deb

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi'
        path: build/bin/tic80

  # === Script stubs ===

    - name: Deploy lua stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi-lua-stub'
        path: build/bin/tic80lua

    - name: Deploy moon stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi-moon-stub'
        path: build/bin/tic80moon

    - name: Deploy fennel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi-fennel-stub'
        path: build/bin/tic80fennel

    - name: Deploy js stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi-js-stub'
        path: build/bin/tic80js

    - name: Deploy wren stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi-wren-stub'
        path: build/bin/tic80wren

    - name: Deploy squirrel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-rpi-squirrel-stub'
        path: build/bin/tic80squirrel

# === Raspberry PI 1-3 Bare Metal ===
  rpi-baremetal:
    runs-on: ubuntu-latest
    container: nesbox/baremetalpi-tic80:latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Prebuild
      run: |
        cd vendor/circle-stdlib
        ./configure -r 3
        make -j$(nproc)
        cd libs/circle/addon/vc4/sound/
        make -j$(nproc)
        cd ../vchiq
        make -j$(nproc)
        cd ../../linux
        make -j$(nproc)

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=baremetalpi/toolchain.cmake ..
        make tic80studio -j$(nproc)
        cd baremetalpi
        make -j$(nproc)
        cd ../../vendor/circle-stdlib/libs/circle/boot/
        make -j$(nproc)

    - name: Pack
      run: |
        cp build/baremetalpi/kernel8-32.img vendor/circle-stdlib/libs/circle/boot/kernel.img
        cp build/baremetalpi/boot/config.txt vendor/circle-stdlib/libs/circle/boot/config.txt

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-baremetal'
        path: |
          vendor/circle-stdlib/libs/circle/boot/config.txt
          vendor/circle-stdlib/libs/circle/boot/kernel.img
          vendor/circle-stdlib/libs/circle/boot/bootcode.bin
          vendor/circle-stdlib/libs/circle/boot/start.elf
          vendor/circle-stdlib/libs/circle/boot/fixup.dat
          vendor/circle-stdlib/libs/circle/boot/LICENCE.broadcom

# === Nintendo 3DS build ===
  nintendo-3ds:
    runs-on: ubuntu-latest
    container: nesbox/devkitpro-tic80:latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$DEVKITPRO/3ds.cmake -DN3DS=TRUE -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        make -j$(nproc)

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-nintendo-3ds'
        path: build/bin/tic80.3dsx

# === MacOS 10.15 ===
  macos:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Install
      run: brew uninstall --ignore-dependencies libidn2

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_STUB=On ..
        cmake --build . --config $BUILD_TYPE --parallel
        cpack
        cp *.dmg tic80.dmg

    - name: Deploy DMG
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-macos-sdl-dmg'
        path: build/tic80.dmg

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-macos-sdl'
        path: build/bin/tic80

  # === Script stubs ===

    - name: Deploy lua stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-macos-sdl-lua-stub'
        path: build/bin/tic80lua

    - name: Deploy moon stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-macos-sdl-moon-stub'
        path: build/bin/tic80moon

    - name: Deploy fennel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-macos-sdl-fennel-stub'
        path: build/bin/tic80fennel

    - name: Deploy js stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-macos-sdl-js-stub'
        path: build/bin/tic80js

    - name: Deploy wren stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-macos-sdl-wren-stub'
        path: build/bin/tic80wren

    - name: Deploy squirrel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-macos-sdl-squirrel-stub'
        path: build/bin/tic80squirrel

# === Android ===
  android:
    runs-on: ubuntu-latest
    container: nesbox/android-tic80:latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      run: |
        cd build/android
        ./gradlew assembleRelease
        cp app/build/outputs/apk/universal/release/app-universal-release.apk tic80.apk

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-android'
        path: build/android/tic80.apk

# === Web Assembly ===
  wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v7

    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      run: |
        cd build
        emcmake cmake -DBUILD_SDLGPU=On -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_STUB=On ..
        cmake --build . --config $BUILD_TYPE --parallel
        cp html/export.html bin/index.html
        cp bin/tic80.js webapp/tic80.js
        cp bin/tic80.wasm webapp/tic80.wasm

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-wasm'
        path: |
          build/bin/tic80.js
          build/bin/tic80.wasm
          build/bin/index.html

    - name: Deploy WebApp
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-webapp'
        path: |
          build/webapp/index.html
          build/webapp/serviceworker.js
          build/webapp/tic80-180.png
          build/webapp/tic80-192.png
          build/webapp/tic80-512.png
          build/webapp/tic80.webmanifest
          build/webapp/tic80.js
          build/webapp/tic80.wasm

  # === Script stubs ===

    - name: Deploy lua stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-wasm-lua-stub'
        path: |
          build/bin/tic80lua.js
          build/bin/tic80lua.wasm
          build/bin/index.html

    - name: Deploy moon stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-wasm-moon-stub'
        path: |
          build/bin/tic80moon.js
          build/bin/tic80moon.wasm
          build/bin/index.html

    - name: Deploy fennel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-wasm-fennel-stub'
        path: |
          build/bin/tic80fennel.js
          build/bin/tic80fennel.wasm
          build/bin/index.html

    - name: Deploy js stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-wasm-js-stub'
        path: |
          build/bin/tic80js.js
          build/bin/tic80js.wasm
          build/bin/index.html

    - name: Deploy wren stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-wasm-wren-stub'
        path: |
          build/bin/tic80wren.js
          build/bin/tic80wren.wasm
          build/bin/index.html

    - name: Deploy squirrel stub
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-wasm-squirrel-stub'
        path: |
          build/bin/tic80squirrel.js
          build/bin/tic80squirrel.wasm
          build/bin/index.html

# === Export ===
  export:
    needs: [windows-sdl, ubuntu-sdl, rpi, macos, wasm]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-windows-sdl
          path: windir

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-ubuntu-sdl
          path: linuxdir

      - name: Download RPI artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-rpi
          path: rpidir

      - name: Download MacOS artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-macos-sdl
          path: macdir

      - name: Download WASM artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-wasm

      - name: Rename
        run: |
          cp windir/* win
          cp linuxdir/* linux
          cp macdir/* mac
          cp rpidir/* rpi
          zip html.zip index.html tic80.js tic80.wasm
          cp html.zip html

      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: 'tic80-export'
          path: |
            win
            linux
            mac
            rpi
            html

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            tic80-ubuntu-sdl
            tic80-ubuntu-sdlgpu
            tic80-rpi
            tic80-macos-sdl

# === Export stub ===
  export-stub:
    needs: [windows-sdl, ubuntu-sdl, rpi, macos, wasm]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [lua, moon, fennel, js, wren, squirrel]

    steps:
      - name: Download Windows ${{ matrix.script }} artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-windows-sdl-${{ matrix.script }}-stub
          path: windir

      - name: Download Ubuntu ${{ matrix.script }} artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-ubuntu-sdl-${{ matrix.script }}-stub
          path: linuxdir

      - name: Download RPI ${{ matrix.script }} artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-rpi-${{ matrix.script }}-stub
          path: rpidir

      - name: Download MacOS ${{ matrix.script }} artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-macos-sdl-${{ matrix.script }}-stub
          path: macdir

      - name: Download WASM ${{ matrix.script }} artifact
        uses: actions/download-artifact@v2
        with:
          name: tic80-wasm-${{ matrix.script }}-stub

      - name: Rename
        run: |
          cp windir/tic80${{ matrix.script }}.exe win${{ matrix.script }}
          cp linuxdir/tic80${{ matrix.script }} linux${{ matrix.script }}
          cp rpidir/tic80${{ matrix.script }} rpi${{ matrix.script }}
          cp macdir/tic80${{ matrix.script }} mac${{ matrix.script }}
          mv -f tic80${{ matrix.script }}.js tic80.js
          zip html${{ matrix.script }}.zip index.html tic80.js tic80${{ matrix.script }}.wasm

      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: 'tic80-export-stub'
          path: |
            win${{ matrix.script }}
            linux${{ matrix.script }}
            rpi${{ matrix.script }}
            mac${{ matrix.script }}
            html${{ matrix.script }}

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            tic80-windows-sdl-${{ matrix.script }}-stub
            tic80-ubuntu-sdl-${{ matrix.script }}-stub
            tic80-rpi-${{ matrix.script }}-stub
            tic80-macos-sdl-${{ matrix.script }}-stub
            tic80-wasm-${{ matrix.script }}-stub
